# Generated by Django 4.0.2 on 2022-02-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='cover_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='thank_you',
            field=models.BooleanField(default=False),
        ),
    ]
